name = "TestReadme"
uuid = "484a2c26-6e88-4a69-ae62-8a3d6c887535"
authors = ["thchr <tchr@mit.edu> and contributors"]
version = "0.1.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
